
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres       # 📌 явно, потому что это имя сервиса в docker-compose
      DB_PORT: ${POSTGRES_PORT} # 📌 явное сопоставление с БД

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data # 📌 явно указываем путь хранения БД
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apply-migration:
    build:
      context: .
      dockerfile: scripts/migration.Dockerfile
    image: migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:super_secret_password@postgres:5432/calendar_db?sslmode=disable
    command: "-dir /app/migrations up"
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:



